name        : vino
version     : 3.18.1
release     : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vino/3.18/vino-3.18.1.tar.xz : 07ec6e78bbecd4ee3fce873eb26932fdda9c7642bb09d17ac36483b996fafe5a
license     : GPL-2.0+
summary     : a VNC server for the GNOME desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(telepathy-glib)
    - pkgconfig(libsecret-1)
    - pkgconfig(NetworkManager)
    - desktop-file-utils
    - libgcrypt-devel
    - pkgconfig(xtst)
    - avahi-devel
    - intltool
    - gnutls
description : |
    a VNC server for the GNOME desktop
setup      : |
    %configure --with-secret
build      : |
    %make
install    : |
    %make_install
