name       : vino
version    : 3.20.2
release    : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vino/3.20/vino-3.20.2.tar.xz : 660488adc1bf577958e783d13f61dbd99c1d9c4e81d2ca063437ea81d39e4413
license    : GPL-2.0+
summary    : a VNC server for the GNOME desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(telepathy-glib)
    - pkgconfig(libsecret-1)
    - pkgconfig(NetworkManager)
    - desktop-file-utils
    - libgcrypt-devel
    - pkgconfig(xtst)
    - avahi-devel
    - intltool
    - gnutls
description: |
    a VNC server for the GNOME desktop
setup      : |
    %configure --with-secret
build      : |
    %make
install    : |
    %make_install
