name        : vino
version     : 3.16.0
release     : 3
source      :
    - http://ftp.gnome.org/pub/gnome/sources/vino/3.16/vino-3.16.0.tar.xz : 608d3613d4e0ad40566759df06587effcfae77f205fce83e3bcf7574bc608dc5
homepage    : http://www.gnome.org/
license     :
    - GPLv2+
summary     : a VNC server for the GNOME desktop
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - desktop-file-utils
    - libgcrypt-devel
    - pkgconfig(xtst)
description : |
    a VNC server for the GNOME desktop
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
