name       : vino
version    : 3.22.0
release    : 14
source     :
    - https://download.gnome.org/sources/vino/3.22/vino-3.22.0.tar.xz : 2911c779b6a2c46e5bc8e5a0c94c2a4d5bd4a1ee7e35f2818702cb13d9d23bab
license    : GPL-2.0-or-later
component  : desktop.utils
summary    : a VNC server for the GNOME desktop
description: |
    a VNC server for the GNOME desktop
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnm)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(sm)
    - pkgconfig(telepathy-glib)
    - pkgconfig(xtst)
    - desktop-file-utils
    - intltool
    - libgcrypt-devel
setup      : |
    %configure --with-secret
build      : |
    %make
install    : |
    %make_install
